on:
  pull_request:
  push:
    branches:
      - master

env:
  METEOR_VERSION: 2.6.1

jobs:
  build:
    name: Build and Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Cache dependencies
        uses: actions/cache@v3
        id: files-cache
        with:
          path: |
            dist
            node_modules
            /tmp/.__tmp_int
            ~/.meteor
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Install/Retrieve Meteor
        if: steps.files-cache.outputs.cache-hit != 'true'
        run: curl https://install.meteor.com/?release=${{ env.METEOR_VERSION }} | /bin/sh
      - name: Install NPM Dependencies
        # Creates dist/ through postinstall->build script
        if: steps.files-cache.outputs.cache-hit != 'true'
        run: ~/.meteor/meteor npm ci
      - name: Run build script
        # Make sure dist/ is up-to-date when package-lock.json hasn't changed
        if: steps.files-cache.outputs.cache-hit == 'true'
        run: ~/.meteor/meteor npm run build

  unit-tests:
    needs: build
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Cache dependencies
        uses: actions/cache@v3
        id: files-cache
        with:
          path: |
            dist
            node_modules
            /tmp/.__tmp_int
            ~/.meteor
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Run test script
        run: ~/.meteor/meteor npm run test

  integration-tests:
    needs: build
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Cache dependencies
        uses: actions/cache@v3
        id: files-cache
        with:
          path: |
            dist
            node_modules
            /tmp/.__tmp_int
            ~/.meteor
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - run: ~/.meteor/meteor npm run prepare-integration-tests
      - name: Run test-integration script (using Xvfb)
        uses: coactions/setup-xvfb@v1
        with: # needs full path to meteor
          run: /home/runner/.meteor/meteor npm run test-integration
